### ISSUE TITLE
Failed to resolve: androidx.activity:activity-ktx:1.3.0-alpha01

### ISSUE THREAD

**Issue by Chozzle** [JetBrains/compose-jb#354]
Trying  to build the imageViewer example but gradle sync shows this error:

```
> Could not find androidx.activity:activity-ktx:1.3.0-alpha01.
     Required by:
         project :android > org.jetbrains.compose.ui:ui-android-debug:0.3.0-build149
```

**Comment by jimgoog** [comment]
Yeah, sorry about that - it's a known issue we discovered a couple of days ago.

@olonho @igordmn This was fixed in master (https://android-review.googlesource.com/c/platform/frameworks/support/+/1576432) so I think if we can push out another build rebased on master, this should go away.

Or alternatively, I think this missing artifact is intended to be published on Wednesday, which should hopefully also resolve this issue.

So a couple of fixes are already in flight, and it's a race to see which fix gets published first.

Sorry for the inconvenience.  It sucks when examples don't build :(.

**Comment by jimgoog** [comment]
@Chozzle As a temporary workaround, I think downgrading from `0.3.0-build149` to `0.3.0-build148` and downgrading Kotlin to `1.4.21-2` would unblock you temporarily, if you really need to get the sample working.  But know a fix is in the works and one way or another should presumably be fixed in a couple of days.

**Comment by jimgoog** [comment]
@Chozzle Or it looks like `0.3.0-build150` just got published.  There are a few things that got deprecated/moved, so some clean up is required if you upgrade, but that should also work.

**Comment by CarsonRedeye** [comment]
No problem I can wait for the fix. It's just for my library compose-macos-theme. It appears that the problem persists with build 150 though

**Comment by sczerwinski** [comment]
Seems that `androidx.activity:activity-ktx:1.3.0-alpha01` is no longer required with `0.3.0-build150`.

Now, however, `ComponentActivity.setContent()` (from package `androidx.compose.ui.platform`) no longer exists. According to deprecation message from `0.3.0-build149`, it has been _moved to the `androidx.activity:activity-compose` artifact_ (which also cannot be resolved). I assume this artifact has only been introduced in AndroidX Activity version `1.3.0-alpha01`?

**Comment by CarsonRedeye** [comment]
That make sense. I wasn't able to build the Android app in my example due to this

**Comment by sczerwinski** [comment]
@CarsonRedeye,

I managed to build it with Kotlin `1.4.30` and JB Compose `0.3.0-build152`, but some additional configuration was necessary.

First, I needed to add a [snapshot repository](https://androidx.dev/snapshots/builds) containing `activity-compose` artifacts:
```kotlin
allprojects {
    repositories {
        // AndroidX snapshots (https://androidx.dev/):
        maven { url = uri("https://androidx.dev/snapshots/builds/7134056/artifacts/repository/") }
    }
}
```
So that I could add `androidx.activity:activity-compose:1.3.0-SNAPSHOT` dependency.

However, `activity-compose` uses other non-existing dependencies, which I couldn't quickly find in the `androidx.dev` snapshots (there's no easy search).

In my case, this worked:
```kotlin
val androidMain by getting {
    dependencies {
        api("androidx.activity:activity-compose:1.3.0-SNAPSHOT") {
            isTransitive = false
        }
    }
}
```
But I guess you might need to browse through the other snapshots to find the missing artifacts, depending on the specific case.

This workaround is probably necessary until `androidx.activity:activity-compose:1.3.0-alpha01` is released.

**Comment by arkivanov** [comment]
Looks like `androidx.activity:activity-compose:1.3.0-alpha01` is released. But I can't compile the TodoApp example with Kotlin `1.4.30` and Compose `0.3.0-build152`. Getting the following error:

```
> Task :android:mergeDebugResources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class androidx.compose.animation.core.Animatable found in modules jetified-animation-core-1.0.0-alpha12-runtime.jar (androidx.compose.animation:animation-core:1.0.0-alpha12) and jetified-animation-core-debug-runtime.jar (org.jetbrains.compose.animation:animation-core-android-debug:0.3.0-build152)
  Duplicate class androidx.compose.animation.core.Animatable$runAnimation$2 found in modules jetified-animation-core-1.0.0-alpha12-runtime.jar (androidx.compose.animation:animation-core:1.0.0-alpha12) and jetified-animation-core-debug-runtime.jar (org.jetbrains.compose.animation:animation-core-android-debug:0.3.0-build152)
  Duplicate class androidx.compose.animation.core.Animatable$runAnimation$2$1 found in modules jetified-animation-core-1.0.0-alpha12-runtime.jar (androidx.compose.animation:animation-core:1.0.0-alpha12) and jetified-animation-core-debug-runtime.jar (org.jetbrains.compose.animation:animation-core-android-debug:0.3.0-build152)
  Duplicate class androidx.compose.animation.core.Animatable$snapTo$2 found in modules jetified-animation-core-1.0.0-alpha12-runtime.jar (androidx.compose.animation:animation-core:1.0.0-alpha12) and jetified-animation-core-debug-runtime.jar (org.jetbrains.compose.animation:animation-core-android-debug:0.3.0-build152)
  Duplicate class androidx.compose.animation.core.Animatable$stop$2 found in modules jetified-animation-core-1.0.0-alpha12-runtime.jar (androidx.compose.animation:animation-core:1.0.0-alpha12) and jetified-animation-core-debug-runtime.jar (org.jetbrains.compose.animation:animation-core-android-debug:0.3.0-build152)
  Duplicate class androidx.compose.animation.core.AnimatableKt found in modules jetified-animation-core-1.0.0-alpha12-runtime.jar (androidx.compose.animation:animation-core:1.0.0-alpha12) and jetified-animation-core-debug-runtime.jar (org.jetbrains.compose.animation:animation-core-android-debug:0.3.0-build152)
... And many many more similar errors
```

**Comment by arkivanov** [comment]
Managed to compile by copy-pasting the moved implementation of `setContent`:

```kotlin
fun ComponentActivity.setContent(
    parent: CompositionContext? = null,
    content: @Composable () -> Unit
) {
    val existingComposeView = window.decorView
        .findViewById<ViewGroup>(android.R.id.content)
        .getChildAt(0) as? ComposeView

    if (existingComposeView != null) with(existingComposeView) {
        setParentCompositionContext(parent)
        setContent(content)
    } else ComposeView(this).apply {
        // Set content and parent **before** setContentView
        // to have ComposeView create the composition on attach
        setParentCompositionContext(parent)
        setContent(content)
        setContentView(this, DefaultLayoutParams)
    }
}

private val DefaultLayoutParams = ViewGroup.LayoutParams(
    ViewGroup.LayoutParams.WRAP_CONTENT,
    ViewGroup.LayoutParams.WRAP_CONTENT
)
```

**Comment by sczerwinski** [comment]
Looks like `androidx.activity:activity-compose:1.3.0-alpha01` uses `androidx.compose.runtime:runtime:1.0.0-alpha12`, which defines:
```kotlin
@Deprecated("Renamed to CompositionContext")
typealias CompositionReference = CompositionContext
```

Since `CompositionContext` is also defined in `compose-jb`, using `androidx.activity:activity-compose` doesn't seem to be a good idea.

I think the `setContent` function copy-pasted by @arkivanov should also be implemented in `compose-jb`.

**Comment by jimgoog** [comment]
Ok, finally published.

You should now be able to use `activity-compose:1.3.0-alpha02`, let me know if you run into any issues with that.

Please make sure you add an explicit dependency on androidx.activity:activity-compose:1.3.0-alpha02 when upgrading to this Compose version https://developer.android.com/jetpack/androidx/releases/activity#1.3.0-alpha02

**Comment by jimgoog** [comment]
Oops, I'll leave this open until we merge an upgraded gradle configuration into the sample.

**Comment by arkivanov** [comment]
@jimgoog  Looks like the errors are still same: "Duplicate class ..."

**Comment by jimgoog** [comment]
Ugg, sounds like maybe we need to cut another release on the Jetbrains side too.

**Comment by arkivanov** [comment]
Alright. The clean build gives me another error now:
```
> Task :android:compileDebugKotlin FAILED
e: androidx.compose.compiler.plugins.kotlin.IncompatibleComposeRuntimeVersionException: You are using an outdated version of Compose Runtime that is not compatible with the version of the Compose Compiler plugin you have installed. The compose compiler plugin you are using (version 1.0.0-alpha13) expects a minimum runtime version of 1.0.0-alpha13. The version of the runtime on the classpath currently is 1.0.0-alpha12.
 
```

**Comment by jimgoog** [comment]
https://github.com/JetBrains/compose-jb/pull/374

**Comment by jimgoog** [comment]
One step at a time.  First step is to get imageviewer building which is done in https://github.com/JetBrains/compose-jb/pull/374

**Comment by arkivanov** [comment]
Thanks @jimgoog , I will apply it to the TodoApo

**Comment by Shabinder** [comment]
> Thanks @jimgoog , I will apply it to the TodoApp

Waiting for it!, decompose was throwing earlier an error like error: Class 'com.arkivanov.decompose.extensions.compose.jetbrains.RouterStateComposableKt' is compiled by an unstable version of the Kotlin compiler and cannot be loaded by this compiler.
decompose gonna get updated too?

**Comment by arkivanov** [comment]
@Shabinder Decompose is already updated, please checkout version 0.1.8.

**Comment by arkivanov** [comment]
> Oops, I'll leave this open until we merge an upgraded gradle configuration into the sample.

@jimgoog The workaround from #374 worked for the example TodoApp, submitted PR. Thanks!

**Comment by jimgoog** [comment]
Ok, sounds like imageviewer and todoapp have been fixed now.
